import { ComponentBase } from './component_base.js';

/**
 * ReactiveComponent adds declarative reactivity to a ComponentBase, driven by data-* attributes
 * in the HTML template:
 *
 *   data-bind='{"elementAttribute":"path.in.state"}'   binds an attribute/property, both ways
 *              (if the element fires "change", the value read flows back into state)
 *   data-class='{"className":"boolean.path"}'          toggles CSS classes
 *   data-style='{"css-property":"path"}'                sets inline style properties
 *   data-ref="name"                                     exposes the element on this.refs.name after rendering
 *   <template data-if="path">...</template>
 *   <template data-else-if="path">...</template>        conditional chain (the first truthy one wins;
 *   <template data-else>...</template>                  data-else is the unconditional fallback)
 *   <template data-for="item in path">...</template>     repeats the content for each item; also accepts
 *                                                         "item, index in path" to expose the index, and an
 *                                                         optional " : field" suffix declaring the item's
 *                                                         identity key (e.g. "e in addresses : uuid") — with a
 *                                                         key (explicit, or inferred from uuid/id), an item's
 *                                                         DOM nodes are reused and moved between renders
 *                                                         instead of being destroyed and recreated
 *
 * Any path used in data-if/data-else-if/data-class accepts a leading "!" to negate it
 * (e.g. data-if="!loading").
 *
 * Subclasses may override:
 *   computed()      -> Object       properties derived from this.state, merged into state for every binding
 *   watchers()      -> Object       {"path": (newValue, oldValue) => {...}} called after each render in
 *                                    which the watched path changed (looked up across raw state + computed)
 */
export class ReactiveComponent extends ComponentBase {

    #state;

    //Latest serialized form of #state (what is — or just arrived — in the data-state attribute).
    //All deduplication goes through comparing this string: it kills the echo of our own setAttribute
    //(attributeChangedCallback fires synchronously inside it) and repeated external writes of the
    //same content, without ever serializing/deserializing the whole object twice just to compare.
    #lastStateJson;

    //Serialized snapshot per watched path, from the last render. We can't just keep a reference to
    //the previous state: nested values are mutated in place by two-way binding, so the "old copy"
    //would point to the same already-mutated object and a nested path's watcher would never fire.
    #watchedSnapshots;

    //Nodes generated by each anchor <template> (conditional or list), keyed by the template element
    //itself — WeakMap: when the template leaves the DOM (e.g. the conditional branch that contained
    //it was removed), the entry dies with it, with no synthetic ids or manual cleanup needed.
    #generatedByAnchor;

    //Which <template> won the conditional chain in the last render, per data-if template (the
    //group's anchor). If the winner hasn't changed, the branch is NOT destroyed/recreated — just
    //reprocessed in place. Without this, any <template data-for> (or any other identity state)
    //living inside a conditional branch would be replaced by a brand-new element on every render,
    //even when the condition didn't change, losing all memory of keyed reconciliation.
    #winnerByAnchor;

    //For keyed lists: template -> Map<item key, that item's nodes>, allowing the DOM nodes of an
    //item whose key is still present to be reused on the next render.
    #itemsByKey;

    //Two-way binding: a single stable listener per element (created once, never removed — it dies
    //with the element). What varies between renders (the current map and scope) lives in this table
    //and is looked up when the event fires, so re-rendering costs one WeakMap.set per element
    //instead of a removeEventListener/addEventListener pair.
    #currentBinding;
    #elementsWithListener;

    constructor(properties, subclassUrl) {
        super(properties, subclassUrl);

        this.#state = undefined;
        this.#lastStateJson = undefined;
        this.#watchedSnapshots = new Map();
        this.#generatedByAnchor = new WeakMap();
        this.#winnerByAnchor = new WeakMap();
        this.#itemsByKey = new WeakMap();
        this.#currentBinding = new WeakMap();
        this.#elementsWithListener = new WeakSet();

        this.refs = {};
    }

    /**
     * Renders once this component's own template and every descendant have finished loading. Any
     * this.#state set before that point (e.g. from the constructor) is already stored and simply
     * gets applied now — see the early return at the top of render().
     */
    onLoad() {
        super.onLoad();
        this.render();
    }



    get state() {
        return this.#state;
    }

    set state(newState) {
        this.updateState(newState);
    }



    static get observedAttributes() {
        return ['data-state'];
    }

    attributeChangedCallback(attributeName, oldValue, newValue) {
        if (attributeName !== 'data-state') {
            return;
        }

        //Blocks the echo of our own setAttribute and identical external writes — by string
        //comparison, before any JSON.parse.
        if (newValue === this.#lastStateJson) {
            return;
        }

        this.#lastStateJson = newValue;
        this.#state = JSON.parse(newValue);

        this.dispatchEvent(new Event('change'));
        this.render();
    }



    /**
     * Override to declare properties derived from this.state. The return value is merged into the
     * raw state (its keys win on conflict) and becomes available to any binding (data-bind, data-if,
     * data-class, data-style, data-for) as if it were a regular piece of state.
     * @returns {Object}
     */
    computed() {
        return {};
    }

    /**
     * Override to react to changes on specific paths (looked up across raw state + computed).
     * Runs after each render in which the watched path's value changed.
     * @returns {Object<string, function(newValue, oldValue)>}
     */
    watchers() {
        return {};
    }



    updateState(newState) {
        //Serialize once: the same string is used both to deduplicate and to write the attribute.
        const json = JSON.stringify(newState);
        if (json === this.#lastStateJson) {
            return;
        }

        this.#state = newState;
        this.#notify(json);
    }

    /**
     * this.#state already reflects the new state; mirror it onto the attribute, notify listeners
     * and re-render. #lastStateJson is updated BEFORE setAttribute because attributeChangedCallback
     * fires synchronously inside it — the string comparison is what cuts off the echo.
     */
    #notify(json) {
        this.#lastStateJson = json;
        this.setAttribute('data-state', json);
        this.dispatchEvent(new Event('change'));
        this.render();
    }

    getValue(object, path) {
        return path.reduce((acc, step) => (acc && acc[step] !== undefined) ? acc[step] : undefined, object);
    }

    setValue(object, path, value) {
        const lastStep = path.pop();
        const target = path.reduce((acc, step) => acc[step], object);
        if (!target) {
            return;
        }

        const currentValue = target[lastStep];

        //If both sides are objects (e.g. a nested component returning the whole item via
        //data-bind='{"data-state":"item"}'), merge into the already-existing object's properties
        //instead of swapping the reference. This matters for list items: the current value is
        //usually the live reference kept inside this.#state, and replacing it with a new object
        //would lose the mutation on the next render (the array would still point to the old object).
        if (currentValue && typeof currentValue === 'object' && !Array.isArray(currentValue) && value && typeof value === 'object' && !Array.isArray(value)) {
            Object.keys(currentValue).forEach(key => delete currentValue[key]);
            Object.assign(currentValue, value);
        } else {
            target[lastStep] = value;
        }
    }



    render() {

        //The template may not have finished loading yet (e.g. state was set before the template
        //fetch completed). In that case there's nothing to render yet; when loading finishes,
        //onLoad() calls render() again with the this.#state that's already stored.
        if (!this.loaded) {
            return;
        }

        const effectiveState = this.#computeEffectiveState();

        this.refs = {};

        this.#processScope(this.rootNode, { state: effectiveState, raw: this.#state || {} });

        this.#collectRefs(this.rootNode);
        this.#runWatchers(effectiveState);
    }

    #computeEffectiveState() {
        return { ...(this.#state || {}), ...(this.computed() || {}) };
    }

    #runWatchers(effectiveState) {
        const watchers = this.watchers() || {};

        Object.entries(watchers).forEach(([path, callback]) => {
            const newValue = this.getValue(effectiveState, path.split('.'));
            const newJson = JSON.stringify(newValue);
            const oldJson = this.#watchedSnapshots.get(path);

            if (newJson !== oldJson) {
                this.#watchedSnapshots.set(path, newJson);
                //The old value is rebuilt from the snapshot (a copy), not a live reference
                const oldValue = oldJson === undefined ? undefined : JSON.parse(oldJson);
                callback.call(this, newValue, oldValue);
            }
        });
    }



    /**
     * Applies every kind of binding (conditionals, lists, bind, class, style) to elements that
     * belong directly to this scope — i.e. that aren't inside a nested list/conditional (those are
     * processed recursively with their own scope when they're created/reused, see
     * #applyConditionals/#applyLists).
     */
    #processScope(root, scope) {
        const bindings = this.#collectBindings(root);

        this.#applyConditionals(bindings.conditionals, scope);
        this.#applyLists(bindings.lists, scope);

        bindings.binds.forEach(element => this.#applyBind(element, scope));
        bindings.classes.forEach(element => this.#applyClasses(element, scope));
        bindings.styles.forEach(element => this.#applyStyles(element, scope));
    }

    /**
     * A single traversal of the scope's subtree, classifying every binding at once — instead of a
     * querySelectorAll plus an ancestor walk per binding type. When it finds the root of a nested
     * scope (a node generated by a list/conditional, marked with data-reactive-scope), it prunes the
     * whole subtree: that content is that scope's own recursion's responsibility. The inner content
     * of a <template> doesn't show up in .children, so it's naturally excluded.
     */
    #collectBindings(root) {
        const bindings = { conditionals: [], lists: [], binds: [], classes: [], styles: [] };

        const visit = (element, isRoot) => {
            if (!isRoot && element.dataset.scope !== undefined) {
                return;
            }

            const dataset = element.dataset;

            if (element.tagName === 'TEMPLATE') {
                if (dataset.if !== undefined) {
                    bindings.conditionals.push(element);
                } else if (dataset.for !== undefined) {
                    bindings.lists.push(element);
                }
                //data-else-if/data-else are picked up through their matching data-if's chain
            } else {
                if (dataset.bind !== undefined) bindings.binds.push(element);
                if (dataset.class !== undefined) bindings.classes.push(element);
                if (dataset.style !== undefined) bindings.styles.push(element);
            }

            for (const child of element.children) {
                visit(child, false);
            }
        };

        if (root.nodeType === Node.ELEMENT_NODE) {
            visit(root, true);
        } else {
            //Shadow root: start from the children (nodes generated at the top of the shadow root
            //belong to their anchor templates and are pruned here — the list/conditional handlers
            //are the ones that reprocess them)
            for (const child of root.children) {
                visit(child, false);
            }
        }

        return bindings;
    }

    #removeGenerated(anchor) {
        (this.#generatedByAnchor.get(anchor) || []).forEach(node => node.remove());
    }

    /**
     * Clones a template's content to instantiate it. Top-level nodes that are just whitespace (text)
     * or comments are discarded: they don't take part in any binding and, left loose between
     * generated items, would pile up on every re-render and break the "already in place" detection
     * used by keyed lists' nextSibling-based reordering.
     */
    #cloneContent(template) {
        const clone = template.content.cloneNode(true);

        Array.from(clone.childNodes).forEach(node => {
            if (node.nodeType === Node.COMMENT_NODE ||
                (node.nodeType === Node.TEXT_NODE && node.textContent.trim() === '')) {
                node.remove();
            }
        });

        const nodes = Array.from(clone.childNodes);
        nodes.forEach(node => {
            if (node.nodeType === Node.ELEMENT_NODE) {
                node.dataset.scope = '';
            }
        });

        return { clone, nodes };
    }

    /**
     * Resolves a data path against the read scope, with support for negation (leading "!").
     */
    #evaluatePath(expression, scope) {
        const cleanExpression = expression.trim();
        const negate = cleanExpression.startsWith('!');
        const path = negate ? cleanExpression.slice(1).trim() : cleanExpression;
        const value = this.getValue(scope.state, path.split('.'));
        return negate ? !value : value;
    }



    // --- Conditionals: data-if / data-else-if / data-else ---

    #applyConditionals(ifTemplates, scope) {
        ifTemplates.forEach(ifTemplate => {

            //Builds the chain: data-if itself followed by consecutive data-else-if/data-else siblings
            const chain = [ifTemplate];
            let next = ifTemplate.nextElementSibling;
            while (next && next.tagName === 'TEMPLATE' && (next.dataset.elseIf !== undefined || next.dataset.else !== undefined)) {
                chain.push(next);
                if (next.dataset.else !== undefined) {
                    break;
                }
                next = next.nextElementSibling;
            }

            let winner = null;
            for (const template of chain) {
                if (template.dataset.else !== undefined) {
                    winner = template;
                    break;
                }
                const expression = template.dataset.if !== undefined ? template.dataset.if : template.dataset.elseIf;
                if (this.#evaluatePath(expression, scope)) {
                    winner = template;
                    break;
                }
            }

            //The chosen branch hasn't changed since the last render (including the case where
            //neither side matched: winner and previousWinner both null): the nodes already exist,
            //they just need to be reprocessed with the current scope — no destroy/recreate. This
            //preserves DOM state and, most importantly, the keyed-reconciliation memory of any
            //data-for living inside the branch (it's indexed by the <template> element, which would
            //stop being the same object if the branch were re-cloned on every render).
            if (winner === this.#winnerByAnchor.get(ifTemplate)) {
                const existingNodes = this.#generatedByAnchor.get(ifTemplate) || [];
                existingNodes.forEach(node => {
                    if (node.nodeType === Node.ELEMENT_NODE) {
                        this.#processScope(node, scope);
                    }
                });
                return;
            }

            this.#removeGenerated(ifTemplate);
            this.#winnerByAnchor.set(ifTemplate, winner);

            if (!winner) {
                this.#generatedByAnchor.set(ifTemplate, []);
                return;
            }

            const { clone, nodes } = this.#cloneContent(winner);
            winner.after(clone);
            this.#generatedByAnchor.set(ifTemplate, nodes);

            //Same scope as the parent: data-if doesn't introduce a new variable, it only decides
            //what shows up
            nodes.forEach(node => {
                if (node.nodeType === Node.ELEMENT_NODE) {
                    this.#processScope(node, scope);
                }
            });
        });
    }



    // --- Lists: data-for="item in path [: keyField]" ---

    #applyLists(templates, scope) {
        templates.forEach(template => {

            const expression = template.dataset.for || '';

            //Syntax: "item in path", "item, index in path", optional " : keyField" suffix
            const [loopExpression, explicitKeyField] = expression.split(':').map(part => part.trim());
            const parts = loopExpression.split(' in ').map(part => part.trim());

            if (parts.length !== 2) {
                console.error(`[${this.constructor.name}] malformed data-for: "${expression}". Use "item in path", "item, index in path" and optionally " : keyField".`);
                this.#removeGenerated(template);
                this.#generatedByAnchor.set(template, []);
                return;
            }

            const [variables, listPath] = parts;
            const [itemVariable, indexVariable] = variables.split(',').map(part => part.trim());

            const list = this.getValue(scope.state, listPath.split('.'));

            if (!Array.isArray(list)) {
                if (list !== undefined) {
                    console.warn(`[${this.constructor.name}] data-for: "${listPath}" is not an array.`);
                }
                this.#removeGenerated(template);
                this.#generatedByAnchor.set(template, []);
                this.#itemsByKey.delete(template);
                return;
            }

            const keyField = explicitKeyField || this.#inferKeyField(list);
            const keys = keyField ? this.#extractKeys(list, keyField) : null;

            if (keys) {
                this.#renderListWithKey(template, list, keys, itemVariable, indexVariable, scope);
            } else {
                this.#renderListWithoutKey(template, list, itemVariable, indexVariable, scope);
            }
        });
    }

    //Without an explicit key, uuid/id are the identity conventions already used across the project (WorkspaceDB)
    #inferKeyField(list) {
        if (list.length === 0) {
            return null;
        }
        for (const field of ['uuid', 'id']) {
            if (list.every(item => item && typeof item === 'object' && item[field] !== undefined)) {
                return field;
            }
        }
        return null;
    }

    //Keys are only usable if all of them exist and are unique in this pass; otherwise, fall back to
    //keyless mode (destroy and rebuild) instead of reusing the wrong item's nodes.
    #extractKeys(list, keyField) {
        const keys = list.map(item => (item && typeof item === 'object') ? item[keyField] : undefined);
        if (keys.some(key => key === undefined) || new Set(keys).size !== keys.length) {
            return null;
        }
        return keys;
    }

    //Item scopes chain by prototype instead of spreading (copying) all of the parent's state on
    //every item — getValue/setValue read through the chain normally.
    #createItemScope(item, index, itemVariable, indexVariable, scope) {
        const state = Object.create(scope.state);
        state[itemVariable] = item;
        if (indexVariable) {
            state[indexVariable] = index;
        }

        const raw = Object.create(scope.raw);
        raw[itemVariable] = item;

        return { state, raw };
    }

    #renderListWithoutKey(template, list, itemVariable, indexVariable, scope) {
        this.#removeGenerated(template);
        this.#itemsByKey.delete(template);

        const generated = [];

        list.forEach((item, index) => {
            const itemScope = this.#createItemScope(item, index, itemVariable, indexVariable, scope);
            const { clone, nodes } = this.#cloneContent(template);

            template.before(clone);
            generated.push(...nodes);

            nodes.forEach(node => {
                if (node.nodeType === Node.ELEMENT_NODE) {
                    this.#processScope(node, itemScope);
                }
            });
        });

        this.#generatedByAnchor.set(template, generated);
    }

    #renderListWithKey(template, list, keys, itemVariable, indexVariable, scope) {
        const previousGeneration = this.#itemsByKey.get(template) || new Map();
        const nextGeneration = new Map();
        const sequence = [];
        const toProcess = [];

        list.forEach((item, index) => {
            const key = keys[index];
            const itemScope = this.#createItemScope(item, index, itemVariable, indexVariable, scope);

            let nodes = previousGeneration.get(key);
            if (nodes) {
                //Key survived: reuse the DOM nodes as-is (focus/scroll/selection state preserved);
                //bindings are reapplied below with the new scope, so the content is correct even if
                //the item's object was replaced with an equivalent one
                previousGeneration.delete(key);
            } else {
                const { clone, nodes: newNodes } = this.#cloneContent(template);
                nodes = newNodes;
                //Temporary position: the ordering step below puts everything in the right place
                template.before(clone);
            }

            nextGeneration.set(key, nodes);
            sequence.push(...nodes);
            toProcess.push([nodes, itemScope]);
        });

        //Items whose keys left the list
        previousGeneration.forEach(nodes => nodes.forEach(node => node.remove()));

        //Minimal-movement ordering: walks the desired sequence back to front, anchored on the
        //template (items always live immediately before it), moving only what's out of place — in a
        //list with no reordering, no node gets touched.
        let reference = template;
        for (let i = sequence.length - 1; i >= 0; i--) {
            const node = sequence[i];
            if (node.nextSibling !== reference) {
                reference.parentNode.insertBefore(node, reference);
            }
            reference = node;
        }

        toProcess.forEach(([nodes, itemScope]) => {
            nodes.forEach(node => {
                if (node.nodeType === Node.ELEMENT_NODE) {
                    this.#processScope(node, itemScope);
                }
            });
        });

        this.#itemsByKey.set(template, nextGeneration);
        this.#generatedByAnchor.set(template, sequence);
    }



    // --- data-bind: attribute/property binding (plus the DOM -> state side, via a stable listener) ---

    #applyBind(element, scope) {
        const bindMap = JSON.parse(element.dataset.bind);

        Object.entries(bindMap).forEach(([elementAttribute, statePath]) => {
            const newValue = this.getValue(scope.state, statePath.split('.'));
            this.#applyAttributeValue(element, elementAttribute, newValue);
        });

        this.#currentBinding.set(element, { bindMap, scope });

        if (!this.#elementsWithListener.has(element)) {
            this.#elementsWithListener.add(element);
            element.addEventListener('change', this.#onContentChange);
        }
    }

    #onContentChange = (event) => {
        const element = event.currentTarget;
        const binding = this.#currentBinding.get(element);
        if (!binding) {
            return;
        }

        Object.entries(binding.bindMap).forEach(([elementAttribute, statePath]) => {
            //Writes to the scope's "raw" object: for top-level state that's the real this.#state, and
            //for a list item it's the array item itself (same reference), so the change propagates
            //without needing to translate the path to be root-relative.
            this.setValue(binding.scope.raw, statePath.split('.'), this.#readAttributeValue(element, elementAttribute));
        });

        //Doesn't go through updateState(): since scope.raw is the very reference of this.#state (or
        //a live object nested inside it), the mutation above already happened BEFORE this point —
        //comparing "before" and "after" objects would never see a difference. The new serialization,
        //though, is still comparable against the last known serialization: if they're equal, the
        //"change" was an echo with no content change (e.g. a parent's own render applying data-state
        //to a reactive child, which synchronously re-fires change) and there's nothing to do.
        const json = JSON.stringify(this.#state);
        if (json === this.#lastStateJson) {
            return;
        }
        this.#notify(json);
    };

    #applyAttributeValue(element, elementAttribute, newValue) {

        if (elementAttribute === "textContent") {

            if (element.textContent !== (newValue ?? '').toString()) {
                element.textContent = newValue;
            }

        } else if (elementAttribute === "checked") {

            if (element.checked !== !!newValue) {
                element.checked = !!newValue;
            }

        } else if (element.tagName.toLowerCase() === 'input' && element.type.toLowerCase() === 'datetime-local') {

            let dateTime = new Date(newValue);
            dateTime.setMinutes(dateTime.getMinutes() - dateTime.getTimezoneOffset());
            let formattedValue = dateTime.toISOString().slice(0, 16);

            if (element.value !== formattedValue) {
                element[elementAttribute] = formattedValue;
            }

        } else if (elementAttribute === "value" && element.value !== newValue) {

            element.value = newValue;

        } else if (element.getAttribute(elementAttribute) !== String(newValue)) {

            let stringValue = (typeof newValue === 'object' && newValue !== null) ? JSON.stringify(newValue) : newValue;
            element.setAttribute(elementAttribute, stringValue);
        }
    }

    #readAttributeValue(element, elementAttribute) {

        if (elementAttribute === "checked") {
            return element.checked;
        }

        //The child element is itself a ReactiveComponent (e.g. data-bind='{"data-state":"item"}' on a
        //nested component): read through its API (this.state), not the literal HTML attribute.
        if (elementAttribute === "data-state" && element.state !== undefined) {
            return element.state;
        }

        return element[elementAttribute];
    }



    // --- data-class: toggles CSS classes ---

    #applyClasses(element, scope) {
        const classMap = JSON.parse(element.dataset.class);

        Object.entries(classMap).forEach(([className, expression]) => {
            element.classList.toggle(className, !!this.#evaluatePath(expression, scope));
        });
    }



    // --- data-style: inline style properties ---

    #applyStyles(element, scope) {
        const styleMap = JSON.parse(element.dataset.style);

        Object.entries(styleMap).forEach(([cssProperty, path]) => {
            const value = this.getValue(scope.state, path.split('.'));

            if (value === undefined || value === null) {
                element.style.removeProperty(cssProperty);
            } else {
                element.style.setProperty(cssProperty, String(value));
            }
        });
    }



    // --- data-ref: exposes elements on this.refs ---

    #collectRefs(root) {
        root.querySelectorAll('[data-ref]').forEach(element => {
            const name = element.dataset.ref;

            if (this.refs[name] === undefined) {
                this.refs[name] = element;
            } else if (Array.isArray(this.refs[name])) {
                this.refs[name].push(element);
            } else {
                this.refs[name] = [this.refs[name], element];
            }
        });
    }
}

window.customElements.define('reactive-component', ReactiveComponent);
